[theme]
primaryColor = "#000000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#000000"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false
