[theme]
primaryColor = "#000000"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableWebsocketCompression = false



[browser]
gatherUsageStats = false
